name: traccar_client
description: Traccar client for Dart. Get real time devices positions from a Traccar server.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  web_socket_channel: ^1.0.12
  dio: ^2.1.2
  latlong: ^0.6.1